name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore Dependencies
      run: dotnet restore

    - name: Restore Dotnet Tools
      run: dotnet tool restore

    - name: Build
      run: dotnet build --no-restore

    - name: Import Test Certificate (Windows)
      if: runner.os == 'Windows'
      run: |
        $AppSettings = Get-Content '.\AdvancedSystems.Security.Tests\appsettings.json' -Raw | ConvertFrom-Json
        $Name = $AppSettings.CertificateStore.Name
        $Location = $AppSettings.CertificateStore.Location
        Import-Certificate -FilePath .\test.cer -CertStoreLocation "Cert:\$Location\$Name"
      shell: powershell

    - name: Import Test Certificate (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        appSettings='./AdvancedSystems.Security.Tests/appsettings.json'
        name=$(jq -r '.CertificateStore.Name' $appSettings)
        location=$(jq -r '.CertificateStore.Location' $appSettings)
        dotnet certificate-tool add -f ./test.cer --store-name $name --store-location $location

    - name: Import Test Certificate (MacOS)
      if: runner.os == 'macOS'
      run: |
        appSettings='./AdvancedSystems.Security.Tests/appsettings.json'
        name=$(jq -r '.CertificateStore.Name' $appSettings)
        location=$(jq -r '.CertificateStore.Location' $appSettings)
        dotnet certificate-tool add -f ./test.cer --store-name $name --store-location $location

    - name: Test
      run: dotnet test --no-build --verbosity normal
